baseurl: /calendario-2016
# url: pretty
logo: images/logo-5p2p-128.png


blog: http://5p2p.it
email: info@5p2p.it
scrivici: http://5p2p.it/scrivici.html

social: 
  - facebook: https://www.facebook.com/5pani2pesci
  - twitter: https://twitter.com/5pani2pesci
  - youtube: https://www.youtube.com/user/5pani2pesci
  # - instagram:

footer:

  5pani2pesci è un progetto per conoscere l'Amore vero, quello che ti cambia la vita. Il nostro augurio e la nostra missione è accompagnarti in questo cammino per aiutarti ad approfondire un incontro autentico col Signore e portare pienamente frutto nella tua vita.
