baseurl: /calendario-2016

blog: http://5p2p.it
email: info@5p2p.it
scrivici: http://5p2p.it/scrivici.html

social: 
  - facebook: https://www.facebook.com/5pani2pesci
  - twitter: https://twitter.com/5pani2pesci
  - youtube: https://www.youtube.com/user/5pani2pesci
  # - instagram: